### ISSUE TITLE
Index.html 0 [BUG]

### ISSUE THREAD

**Issue by Andyauk** [BerkieBb/qb-target#107]
**Describe the bug**
F8 in-game error.

**To Reproduce**
It seems to not always pick up the target.

So I goto a store, ALT on the ped and the blue doesn't appear, but if I click when holding ALT the error message will appear.

But if I let go of ALT, it will pick t up and go blue. 

So it's like a delay not sure

**Expected behavior**
press ALT blue colour mouse click open.

**Screenshots**

<a href="https://ibb.co/265hJ7H"><img src="https://i.ibb.co/H2X4ZD3/target.png" alt="target" border="0"></a>

**Additional context**
the issue I get, with and without no edits.

**Comment by BerkieBb** [comment]
Have you downloaded the newest version?

**Comment by Andyauk** [comment]
> Have you downloaded the newest version?

yes I have. I've tried it with and without my edits.

**Comment by BerkieBb** [comment]
Have you restarted the server in between these tests?

**Comment by Andyauk** [comment]
> Have you restarted the server in between these tests?

I have hard resettled, a few times today but I added the update yester when you put it out. the only thing I can see different with and without edits I also set `Config.EnableDefaultOptions = true` from false and `Config.MaxDistance = 5.0` from 7/0

**Comment by BerkieBb** [comment]
I think there was a bug which I fixed with V5.3.3, please check if V5.3.3 fixes your issue

**Comment by Andyauk** [comment]
> I think there was a bug which I fixed with V5.3.3, please check if V5.3.3 fixes your issue

I still have the issue, but I'll recheck when I get home that I have the latest copy. I'm sure I do. But I was still getting the error yesterday. The only thing I can think of if I do have the latest on. Is to remove the hardlink of it.

**Comment by Andyauk** [comment]
> I think there was a bug which I fixed with V5.3.3, please check if V5.3.3 fixes your issue

I've updated my bud info to see if that helps you. I'll let you know if I have the new copy in a bit.

**Comment by BerkieBb** [comment]
I can't figure out why this error happens, it seems to happen randomly for me

**Comment by Andyauk** [comment]
> I can't figure out why this error happens, it seems to happen randomly for me

It's very randomly true, and hard to proc it. I make notes when things happen, but this issue can be from anything.

**Comment by BerkieBb** [comment]
This should be fixed with https://github.com/BerkieBb/qb-target/releases/tag/5.3.8
